version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: luismaDb
      MYSQL_DATABASE: servers
    ports:
      - "33060:3306"
    volumes:
      - /home/luisma/mysql-data:/var/lib/mysql