
spring:
  datasource:
    password: luismaDb
    url: jdbc:mysql://localhost:33060/servers
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true